env:
  APP_NAME: ${BUILDKITE_PIPELINE_SLUG}
  IMAGE_REPO: ghcr.io/theopenlane/${APP_NAME}
  IMAGE_TAG: ${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT:0:8}

steps:
  - group: ":docker: Image Build"
    key: "image-build"
    steps:
      - label: ":docker: docker pr build"
        key: "docker-pr-build"
        if: build.branch != "main" && build.tag == null
        commands: |
          #!/bin/bash
          ls
        plugins:
          - cluster-secrets#v1.0.0:
              variables:
                SECRET_GHCR_PUBLISH_TOKEN: SECRET_GHCR_PUBLISH_TOKEN
          - docker-login#v3.0.0:
              username: theopenlane-bender
              password-env: SECRET_GHCR_PUBLISH_TOKEN
              server: ghcr.io
          - theopenlane/docker-metadata#v1.0.1:
              images:
                - "${IMAGE_REPO}"
              extra_tags:
                - "${IMAGE_TAG}"
          - theopenlane/container-build#v1.1.1:
              dockerfile: Dockerfile
              push: false
              build-args:
                - NAME=${APP_NAME}
          - equinixmetal-buildkite/trivy#v1.20.0:
              severity: CRITICAL,HIGH
              ignore-unfixed: true
              scanners: misconfig,vuln
              skip-files: 'cosign.key'
              ignorefile: ".trivyignore.yaml"
              trivy-version: "0.58.1"
              exit-code: 0 # Ignore trivy exit code, the scanner isn't taking the correct params
      - label: ":docker: docker build and publish"
        key: "docker-build"
        if: build.branch == "main"
        commands: |
          #!/bin/bash
          ls
        plugins:
          - cluster-secrets#v1.0.0:
              variables:
                SECRET_GHCR_PUBLISH_TOKEN: SECRET_GHCR_PUBLISH_TOKEN
          - docker-login#v3.0.0:
              username: theopenlane-bender
              password-env: SECRET_GHCR_PUBLISH_TOKEN
              server: ghcr.io
          - theopenlane/docker-metadata#v1.0.1:
              images:
                - "${IMAGE_REPO}"
              extra_tags:
                - "${IMAGE_TAG}"
                - "latest"
          - theopenlane/container-build#v1.1.1:
              dockerfile: Dockerfile
              push: true
              build-args:
                - NAME=${APP_NAME}
          - equinixmetal-buildkite/trivy#v1.20.0:
              severity: CRITICAL,HIGH
              ignore-unfixed: true
              scanners: misconfig,vuln
              skip-files: 'cosign.key'
              ignorefile: ".trivyignore.yaml"
              trivy-version: "0.58.1"
              exit-code: 0 # Ignore trivy exit code, the scanner isn't taking the correct params
      - label: ":docker: docker build and publish"
        key: "docker-build-and-tag"
        if: build.tag != null
        commands: |
          #!/bin/bash
          ls
        plugins:
          - cluster-secrets#v1.0.0:
              variables:
                SECRET_GHCR_PUBLISH_TOKEN: SECRET_GHCR_PUBLISH_TOKEN
          - docker-login#v3.0.0:
              username: theopenlane-bender
              password-env: SECRET_GHCR_PUBLISH_TOKEN
              server: ghcr.io
          - theopenlane/docker-metadata#v1.0.1:
              images:
                - "${IMAGE_REPO}"
              extra_tags:
                - "${BUILDKITE_TAG}"
          - theopenlane/container-build#v1.1.1:
              dockerfile: Dockerfile
              push: true
              build-args:
                - NAME=${APP_NAME}
          - equinixmetal-buildkite/trivy#v1.20.0:
              severity: CRITICAL,HIGH
              ignore-unfixed: true
              scanners: misconfig,vuln
              skip-files: 'cosign.key'
              ignorefile: ".trivyignore.yaml"
              trivy-version: "0.58.1"
              exit-code: 0 # Ignore trivy exit code, the scanner isn't taking the correct params
